# Generated by Django 3.2.6 on 2021-08-22 04:38

import demo.cr_process.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('orderid', models.CharField(default=demo.cr_process.models.get_crid, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('vendor', models.CharField(choices=[('OC', 'OK Circuits'), ('DV', 'Denivern')], max_length=128)),
                ('product_name', models.CharField(choices=[('OC', 'OK Circuits'), ('DV', 'Denivern')], max_length=128)),
                ('severity', models.CharField(choices=[('OC', 'OK Circuits'), ('DV', 'Denivern')], max_length=128)),
                ('cr_type', models.CharField(choices=[('OC', 'OK Circuits'), ('DV', 'Denivern')], max_length=128)),
                ('affected_device', models.CharField(choices=[('OC', 'OK Circuits'), ('DV', 'Denivern')], max_length=128)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('l1_approve', models.BooleanField(default=True)),
                ('l2_approve', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
