# Generated by Django 3.2.6 on 2022-10-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_process', '0002_auto_20210829_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crprocess',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crprocess',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
